blueprint:
  name: Notification to Close a Window
  description: Notification to close windows if it is cold outside
  domain: automation
  input: 
    contact_sensor: 
      name: Window Sensor
      description: 'The window or door sensor that triggers the automation.'
      selector: 
        entity:
          domain: binary_sensor
    first_timer:
      name: 'First timer'
      description: 'The first notification timer (in minutes).'
      default: 10
      selector: 
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    second_timer:
      name: 'Second timer'
      description: 'The second notification timer (in minutes).'
      default: 15
      selector: 
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    temperature:
      name: 'Temperature'
      description: 'The outside temperature below which the notification should be sent.'
      default: 20
      selector: 
        number:
          min: 0
          step: 1
          max: 25
          mode: slider
    temperature_outside:
      name: 'Outside temperature entity'
      description: 'Weather entity that provides the outside temperature'
      selector:
        entity:
          domain: weather

# We will have two triggers, for the two different reminders. 
# However, a reminder will be ignored if the door or window is already closed by then. 
trigger:
- platform: state
  entity_id: !input contact_sensor
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input first_timer
    seconds: 0
- platform: state
  entity_id: !input contact_sensor
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input second_timer
    seconds: 0

# Two conditions:
# 1. The door or window should still be open. 
# 2. The temperature reading must be below the set value. 
condition:
- condition: state
  entity_id: !input contact_sensor
  state: 'on'
- condition: numeric_state
  entity_id: !input temperature_outside
  attribute: temperature
  below: !input temperature

action:
  service: notify.matrix_notify
  message: 'Fenster {{trigger.to_state.attributes.friendly_name}} schließen.'

mode: single

